spring:
  redis:
    host: 139.9.65.255
    port: 6379
    password:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        #后台管理
        - id: mall-backend-route
          uri: lb://mall-backend
          predicates:
            - Path=/api/system/**
          filters:
            - StripPrefix=1
        #商品模块
        - id: mall-product-route
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**
          filters:
            - StripPrefix=1
        #会员模块
        - id: mall-member-route
          uri: lb://mall-member
          predicates:
            - Path=/api/member/**
          filters:
            - StripPrefix=1
        #仓储模块
        - id: mall-ware-route
          uri: lb://mall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - StripPrefix=1
        #第三方服务模块
        - id: third-party-route
          uri: lb://mall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - StripPrefix=1

        - id: mall_host_route
          uri: lb://mall-product
          predicates:
            - Host=**.mall.com

    nacos:
      discovery:
        server-addr: 139.9.65.255:8848

#白名单
ignore:
  whites:
    - /api/system/code
    - /api/system/login
    - /api/system/logout