
#数据库链接
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.112.242.184:3306/mall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: root
  redis:
    host: 47.112.242.184
    port: 6379
    password:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false #关闭缓存
#mybatisPlus配置
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1 #代表删除
      logic-not-delete-value: 0 #代表未删除
logging:
  level:
    com.yxx.mall: debug

