spring:
  cloud:
    nacos:
      discovery:
        server-addr: 47.112.242.184:8848
    alicloud:
      access-key: xxxx
      secret-key: xxxx
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
        bucket: mall-xyong