spring:
  cloud:
    nacos:
      discovery:
        server-addr: 47.112.242.184:8848
    alicloud:
      access-key: TAI5tLfjUrHWKH2VbnTgQo
      secret-key: lk4TA28U5wOIdHOmD1Z9FMzfOvA
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
        bucket: mall-xyong